apiVersion: apps/v1
kind: Deployment
metadata:
  name: os2-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os2-client
  template:
    metadata:
        labels:
          app: os2-client
    spec:
      containers:
        - name: os2-client
          image: mostafakhairy0305927/os2-client
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80