apiVersion: v1
kind: Service
metadata:
  name: service-server
  namespace: default
  labels:
    app: os2-server
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30003
  selector:
    app: os2-server