apiVersion: v1
kind: Service
metadata:
  name: service-client
  namespace: default
  labels:
    app: os2-client
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: os2-client