apiVersion: v1
kind: Service
metadata:
  name: service-names
  namespace: default
  labels:
    app: os-names
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
    app: os-names